line-length = 121
indent-width = 4
target-version = "py310"

[lint]
extend-select = [
    "ALL",
]

ignore = [
    "ANN204", # annotate `__init__` ???????
    "ANN002", # annotate *args :/
    "ANN003", # annotate **kwargs ...
    "Q000", # single quota demand
    "ANN401", # type hint Any
    "BLE001", # too bload exceptions

    # todo
    "LOG",
    "B024",
    "C901",
    # todo check
    "D",
    "PT",
    "FIX",
    "S",
    "TD",
    "FBT",
    "SLF",
    "BLE",
    "RUF",
    "SIM",
    "DTZ",
    "PLW",
    "PLR",
]

[format]
indent-style = "space"
quote-style = "single"

[lint.per-file-ignores]
"__init__.py" = ["F403", "I001"]
"**/{tests,examples}/*" = ["ALL"]

#"**/{alembic}/*" = ["ALL"]